/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as EntregadoresRouteImport } from './routes/entregadores'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntregadoresIndexRouteImport } from './routes/entregadores.index'
import { Route as EntregadorIndexRouteImport } from './routes/entregador.index'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as EntregadoresPerfilRouteImport } from './routes/entregadores.perfil'
import { Route as EntregadoresParceirosRouteImport } from './routes/entregadores.parceiros'
import { Route as EntregadoresPainelRouteImport } from './routes/entregadores.painel'
import { Route as EntregadoresNovaSenhaRouteImport } from './routes/entregadores.nova-senha'
import { Route as EntregadoresLoginRouteImport } from './routes/entregadores.login'
import { Route as EntregadoresCadastroRouteImport } from './routes/entregadores.cadastro'
import { Route as EntregadorIdRouteImport } from './routes/entregador.$id'
import { Route as EntrarEntregadorSlugRouteImport } from './routes/entrar-entregador.$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedMasterRouteRouteImport } from './routes/_authenticated/master/route'
import { Route as AuthenticatedEmpresaRouteRouteImport } from './routes/_authenticated/empresa/route'
import { Route as AuthenticatedMasterIndexRouteImport } from './routes/_authenticated/master/index'
import { Route as AuthenticatedEmpresaIndexRouteImport } from './routes/_authenticated/empresa/index'
import { Route as AuthenticatedMasterUsuariosRouteImport } from './routes/_authenticated/master/usuarios'
import { Route as AuthenticatedMasterSegurancaRouteImport } from './routes/_authenticated/master/seguranca'
import { Route as AuthenticatedMasterRelatoriosRouteImport } from './routes/_authenticated/master/relatorios'
import { Route as AuthenticatedMasterPlanosRouteImport } from './routes/_authenticated/master/planos'
import { Route as AuthenticatedMasterMensalidadesRouteImport } from './routes/_authenticated/master/mensalidades'
import { Route as AuthenticatedMasterEntregadoresRouteImport } from './routes/_authenticated/master/entregadores'
import { Route as AuthenticatedMasterEmpresasRouteImport } from './routes/_authenticated/master/empresas'
import { Route as AuthenticatedEmpresaRelatoriosRouteImport } from './routes/_authenticated/empresa/relatorios'
import { Route as AuthenticatedEmpresaProdutosRouteImport } from './routes/_authenticated/empresa/produtos'
import { Route as AuthenticatedEmpresaPlanosRouteImport } from './routes/_authenticated/empresa/planos'
import { Route as AuthenticatedEmpresaPedidosSimplesRouteImport } from './routes/_authenticated/empresa/pedidos-simples'
import { Route as AuthenticatedEmpresaPedidosRouteImport } from './routes/_authenticated/empresa/pedidos'
import { Route as AuthenticatedEmpresaPdvRouteImport } from './routes/_authenticated/empresa/pdv'
import { Route as AuthenticatedEmpresaMesasRouteImport } from './routes/_authenticated/empresa/mesas'
import { Route as AuthenticatedEmpresaEntregadoresRouteImport } from './routes/_authenticated/empresa/entregadores'
import { Route as AuthenticatedEmpresaCuponsRouteImport } from './routes/_authenticated/empresa/cupons'
import { Route as AuthenticatedEmpresaConfiguracoesRouteImport } from './routes/_authenticated/empresa/configuracoes'
import { Route as AuthenticatedEmpresaClientesRouteImport } from './routes/_authenticated/empresa/clientes'
import { Route as AuthenticatedEmpresaCategoriasRouteImport } from './routes/_authenticated/empresa/categorias'
import { Route as AuthenticatedEmpresaAvaliacoesRouteImport } from './routes/_authenticated/empresa/avaliacoes'
import { Route as AuthenticatedEmpresaAnalyticsRouteImport } from './routes/_authenticated/empresa/analytics'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadoresRoute = EntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadoresIndexRoute = EntregadoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntregadoresRoute,
} as any)
const EntregadorIndexRoute = EntregadorIndexRouteImport.update({
  id: '/entregador/',
  path: '/entregador/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadoresPerfilRoute = EntregadoresPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => EntregadoresRoute,
} as any)
const EntregadoresParceirosRoute = EntregadoresParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => EntregadoresRoute,
} as any)
const EntregadoresPainelRoute = EntregadoresPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => EntregadoresRoute,
} as any)
const EntregadoresNovaSenhaRoute = EntregadoresNovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => EntregadoresRoute,
} as any)
const EntregadoresLoginRoute = EntregadoresLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EntregadoresRoute,
} as any)
const EntregadoresCadastroRoute = EntregadoresCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => EntregadoresRoute,
} as any)
const EntregadorIdRoute = EntregadorIdRouteImport.update({
  id: '/entregador/$id',
  path: '/entregador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarEntregadorSlugRoute = EntrarEntregadorSlugRouteImport.update({
  id: '/entrar-entregador/$slug',
  path: '/entrar-entregador/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterRouteRoute =
  AuthenticatedMasterRouteRouteImport.update({
    id: '/master',
    path: '/master',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaRouteRoute =
  AuthenticatedEmpresaRouteRouteImport.update({
    id: '/empresa',
    path: '/empresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterIndexRoute =
  AuthenticatedMasterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedEmpresaIndexRoute =
  AuthenticatedEmpresaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedMasterUsuariosRoute =
  AuthenticatedMasterUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedMasterSegurancaRoute =
  AuthenticatedMasterSegurancaRouteImport.update({
    id: '/seguranca',
    path: '/seguranca',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedMasterRelatoriosRoute =
  AuthenticatedMasterRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedMasterPlanosRoute =
  AuthenticatedMasterPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedMasterMensalidadesRoute =
  AuthenticatedMasterMensalidadesRouteImport.update({
    id: '/mensalidades',
    path: '/mensalidades',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedMasterEntregadoresRoute =
  AuthenticatedMasterEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedMasterEmpresasRoute =
  AuthenticatedMasterEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedEmpresaRelatoriosRoute =
  AuthenticatedEmpresaRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaProdutosRoute =
  AuthenticatedEmpresaProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaPlanosRoute =
  AuthenticatedEmpresaPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaPedidosSimplesRoute =
  AuthenticatedEmpresaPedidosSimplesRouteImport.update({
    id: '/pedidos-simples',
    path: '/pedidos-simples',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaPedidosRoute =
  AuthenticatedEmpresaPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaPdvRoute = AuthenticatedEmpresaPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedEmpresaRouteRoute,
} as any)
const AuthenticatedEmpresaMesasRoute =
  AuthenticatedEmpresaMesasRouteImport.update({
    id: '/mesas',
    path: '/mesas',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaEntregadoresRoute =
  AuthenticatedEmpresaEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaCuponsRoute =
  AuthenticatedEmpresaCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaConfiguracoesRoute =
  AuthenticatedEmpresaConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaClientesRoute =
  AuthenticatedEmpresaClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaCategoriasRoute =
  AuthenticatedEmpresaCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaAvaliacoesRoute =
  AuthenticatedEmpresaAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)
const AuthenticatedEmpresaAnalyticsRoute =
  AuthenticatedEmpresaAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedEmpresaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entregadores': typeof EntregadoresRouteWithChildren
  '/lojas': typeof LojasRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/empresa': typeof AuthenticatedEmpresaRouteRouteWithChildren
  '/master': typeof AuthenticatedMasterRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/entrar-entregador/$slug': typeof EntrarEntregadorSlugRoute
  '/entregador/$id': typeof EntregadorIdRoute
  '/entregadores/cadastro': typeof EntregadoresCadastroRoute
  '/entregadores/login': typeof EntregadoresLoginRoute
  '/entregadores/nova-senha': typeof EntregadoresNovaSenhaRoute
  '/entregadores/painel': typeof EntregadoresPainelRoute
  '/entregadores/parceiros': typeof EntregadoresParceirosRoute
  '/entregadores/perfil': typeof EntregadoresPerfilRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/entregador/': typeof EntregadorIndexRoute
  '/entregadores/': typeof EntregadoresIndexRoute
  '/empresa/analytics': typeof AuthenticatedEmpresaAnalyticsRoute
  '/empresa/avaliacoes': typeof AuthenticatedEmpresaAvaliacoesRoute
  '/empresa/categorias': typeof AuthenticatedEmpresaCategoriasRoute
  '/empresa/clientes': typeof AuthenticatedEmpresaClientesRoute
  '/empresa/configuracoes': typeof AuthenticatedEmpresaConfiguracoesRoute
  '/empresa/cupons': typeof AuthenticatedEmpresaCuponsRoute
  '/empresa/entregadores': typeof AuthenticatedEmpresaEntregadoresRoute
  '/empresa/mesas': typeof AuthenticatedEmpresaMesasRoute
  '/empresa/pdv': typeof AuthenticatedEmpresaPdvRoute
  '/empresa/pedidos': typeof AuthenticatedEmpresaPedidosRoute
  '/empresa/pedidos-simples': typeof AuthenticatedEmpresaPedidosSimplesRoute
  '/empresa/planos': typeof AuthenticatedEmpresaPlanosRoute
  '/empresa/produtos': typeof AuthenticatedEmpresaProdutosRoute
  '/empresa/relatorios': typeof AuthenticatedEmpresaRelatoriosRoute
  '/master/empresas': typeof AuthenticatedMasterEmpresasRoute
  '/master/entregadores': typeof AuthenticatedMasterEntregadoresRoute
  '/master/mensalidades': typeof AuthenticatedMasterMensalidadesRoute
  '/master/planos': typeof AuthenticatedMasterPlanosRoute
  '/master/relatorios': typeof AuthenticatedMasterRelatoriosRoute
  '/master/seguranca': typeof AuthenticatedMasterSegurancaRoute
  '/master/usuarios': typeof AuthenticatedMasterUsuariosRoute
  '/empresa/': typeof AuthenticatedEmpresaIndexRoute
  '/master/': typeof AuthenticatedMasterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lojas': typeof LojasRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/entrar-entregador/$slug': typeof EntrarEntregadorSlugRoute
  '/entregador/$id': typeof EntregadorIdRoute
  '/entregadores/cadastro': typeof EntregadoresCadastroRoute
  '/entregadores/login': typeof EntregadoresLoginRoute
  '/entregadores/nova-senha': typeof EntregadoresNovaSenhaRoute
  '/entregadores/painel': typeof EntregadoresPainelRoute
  '/entregadores/parceiros': typeof EntregadoresParceirosRoute
  '/entregadores/perfil': typeof EntregadoresPerfilRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/entregador': typeof EntregadorIndexRoute
  '/entregadores': typeof EntregadoresIndexRoute
  '/empresa/analytics': typeof AuthenticatedEmpresaAnalyticsRoute
  '/empresa/avaliacoes': typeof AuthenticatedEmpresaAvaliacoesRoute
  '/empresa/categorias': typeof AuthenticatedEmpresaCategoriasRoute
  '/empresa/clientes': typeof AuthenticatedEmpresaClientesRoute
  '/empresa/configuracoes': typeof AuthenticatedEmpresaConfiguracoesRoute
  '/empresa/cupons': typeof AuthenticatedEmpresaCuponsRoute
  '/empresa/entregadores': typeof AuthenticatedEmpresaEntregadoresRoute
  '/empresa/mesas': typeof AuthenticatedEmpresaMesasRoute
  '/empresa/pdv': typeof AuthenticatedEmpresaPdvRoute
  '/empresa/pedidos': typeof AuthenticatedEmpresaPedidosRoute
  '/empresa/pedidos-simples': typeof AuthenticatedEmpresaPedidosSimplesRoute
  '/empresa/planos': typeof AuthenticatedEmpresaPlanosRoute
  '/empresa/produtos': typeof AuthenticatedEmpresaProdutosRoute
  '/empresa/relatorios': typeof AuthenticatedEmpresaRelatoriosRoute
  '/master/empresas': typeof AuthenticatedMasterEmpresasRoute
  '/master/entregadores': typeof AuthenticatedMasterEntregadoresRoute
  '/master/mensalidades': typeof AuthenticatedMasterMensalidadesRoute
  '/master/planos': typeof AuthenticatedMasterPlanosRoute
  '/master/relatorios': typeof AuthenticatedMasterRelatoriosRoute
  '/master/seguranca': typeof AuthenticatedMasterSegurancaRoute
  '/master/usuarios': typeof AuthenticatedMasterUsuariosRoute
  '/empresa': typeof AuthenticatedEmpresaIndexRoute
  '/master': typeof AuthenticatedMasterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/entregadores': typeof EntregadoresRouteWithChildren
  '/lojas': typeof LojasRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRouteRouteWithChildren
  '/_authenticated/master': typeof AuthenticatedMasterRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/entrar-entregador/$slug': typeof EntrarEntregadorSlugRoute
  '/entregador/$id': typeof EntregadorIdRoute
  '/entregadores/cadastro': typeof EntregadoresCadastroRoute
  '/entregadores/login': typeof EntregadoresLoginRoute
  '/entregadores/nova-senha': typeof EntregadoresNovaSenhaRoute
  '/entregadores/painel': typeof EntregadoresPainelRoute
  '/entregadores/parceiros': typeof EntregadoresParceirosRoute
  '/entregadores/perfil': typeof EntregadoresPerfilRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/entregador/': typeof EntregadorIndexRoute
  '/entregadores/': typeof EntregadoresIndexRoute
  '/_authenticated/empresa/analytics': typeof AuthenticatedEmpresaAnalyticsRoute
  '/_authenticated/empresa/avaliacoes': typeof AuthenticatedEmpresaAvaliacoesRoute
  '/_authenticated/empresa/categorias': typeof AuthenticatedEmpresaCategoriasRoute
  '/_authenticated/empresa/clientes': typeof AuthenticatedEmpresaClientesRoute
  '/_authenticated/empresa/configuracoes': typeof AuthenticatedEmpresaConfiguracoesRoute
  '/_authenticated/empresa/cupons': typeof AuthenticatedEmpresaCuponsRoute
  '/_authenticated/empresa/entregadores': typeof AuthenticatedEmpresaEntregadoresRoute
  '/_authenticated/empresa/mesas': typeof AuthenticatedEmpresaMesasRoute
  '/_authenticated/empresa/pdv': typeof AuthenticatedEmpresaPdvRoute
  '/_authenticated/empresa/pedidos': typeof AuthenticatedEmpresaPedidosRoute
  '/_authenticated/empresa/pedidos-simples': typeof AuthenticatedEmpresaPedidosSimplesRoute
  '/_authenticated/empresa/planos': typeof AuthenticatedEmpresaPlanosRoute
  '/_authenticated/empresa/produtos': typeof AuthenticatedEmpresaProdutosRoute
  '/_authenticated/empresa/relatorios': typeof AuthenticatedEmpresaRelatoriosRoute
  '/_authenticated/master/empresas': typeof AuthenticatedMasterEmpresasRoute
  '/_authenticated/master/entregadores': typeof AuthenticatedMasterEntregadoresRoute
  '/_authenticated/master/mensalidades': typeof AuthenticatedMasterMensalidadesRoute
  '/_authenticated/master/planos': typeof AuthenticatedMasterPlanosRoute
  '/_authenticated/master/relatorios': typeof AuthenticatedMasterRelatoriosRoute
  '/_authenticated/master/seguranca': typeof AuthenticatedMasterSegurancaRoute
  '/_authenticated/master/usuarios': typeof AuthenticatedMasterUsuariosRoute
  '/_authenticated/empresa/': typeof AuthenticatedEmpresaIndexRoute
  '/_authenticated/master/': typeof AuthenticatedMasterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/entregadores'
    | '/lojas'
    | '/nova-senha'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/empresa'
    | '/master'
    | '/app'
    | '/onboarding'
    | '/entrar-entregador/$slug'
    | '/entregador/$id'
    | '/entregadores/cadastro'
    | '/entregadores/login'
    | '/entregadores/nova-senha'
    | '/entregadores/painel'
    | '/entregadores/parceiros'
    | '/entregadores/perfil'
    | '/loja/$slug'
    | '/pedido/$id'
    | '/entregador/'
    | '/entregadores/'
    | '/empresa/analytics'
    | '/empresa/avaliacoes'
    | '/empresa/categorias'
    | '/empresa/clientes'
    | '/empresa/configuracoes'
    | '/empresa/cupons'
    | '/empresa/entregadores'
    | '/empresa/mesas'
    | '/empresa/pdv'
    | '/empresa/pedidos'
    | '/empresa/pedidos-simples'
    | '/empresa/planos'
    | '/empresa/produtos'
    | '/empresa/relatorios'
    | '/master/empresas'
    | '/master/entregadores'
    | '/master/mensalidades'
    | '/master/planos'
    | '/master/relatorios'
    | '/master/seguranca'
    | '/master/usuarios'
    | '/empresa/'
    | '/master/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/lojas'
    | '/nova-senha'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/app'
    | '/onboarding'
    | '/entrar-entregador/$slug'
    | '/entregador/$id'
    | '/entregadores/cadastro'
    | '/entregadores/login'
    | '/entregadores/nova-senha'
    | '/entregadores/painel'
    | '/entregadores/parceiros'
    | '/entregadores/perfil'
    | '/loja/$slug'
    | '/pedido/$id'
    | '/entregador'
    | '/entregadores'
    | '/empresa/analytics'
    | '/empresa/avaliacoes'
    | '/empresa/categorias'
    | '/empresa/clientes'
    | '/empresa/configuracoes'
    | '/empresa/cupons'
    | '/empresa/entregadores'
    | '/empresa/mesas'
    | '/empresa/pdv'
    | '/empresa/pedidos'
    | '/empresa/pedidos-simples'
    | '/empresa/planos'
    | '/empresa/produtos'
    | '/empresa/relatorios'
    | '/master/empresas'
    | '/master/entregadores'
    | '/master/mensalidades'
    | '/master/planos'
    | '/master/relatorios'
    | '/master/seguranca'
    | '/master/usuarios'
    | '/empresa'
    | '/master'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/entregadores'
    | '/lojas'
    | '/nova-senha'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/empresa'
    | '/_authenticated/master'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/entrar-entregador/$slug'
    | '/entregador/$id'
    | '/entregadores/cadastro'
    | '/entregadores/login'
    | '/entregadores/nova-senha'
    | '/entregadores/painel'
    | '/entregadores/parceiros'
    | '/entregadores/perfil'
    | '/loja/$slug'
    | '/pedido/$id'
    | '/entregador/'
    | '/entregadores/'
    | '/_authenticated/empresa/analytics'
    | '/_authenticated/empresa/avaliacoes'
    | '/_authenticated/empresa/categorias'
    | '/_authenticated/empresa/clientes'
    | '/_authenticated/empresa/configuracoes'
    | '/_authenticated/empresa/cupons'
    | '/_authenticated/empresa/entregadores'
    | '/_authenticated/empresa/mesas'
    | '/_authenticated/empresa/pdv'
    | '/_authenticated/empresa/pedidos'
    | '/_authenticated/empresa/pedidos-simples'
    | '/_authenticated/empresa/planos'
    | '/_authenticated/empresa/produtos'
    | '/_authenticated/empresa/relatorios'
    | '/_authenticated/master/empresas'
    | '/_authenticated/master/entregadores'
    | '/_authenticated/master/mensalidades'
    | '/_authenticated/master/planos'
    | '/_authenticated/master/relatorios'
    | '/_authenticated/master/seguranca'
    | '/_authenticated/master/usuarios'
    | '/_authenticated/empresa/'
    | '/_authenticated/master/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EntregadoresRoute: typeof EntregadoresRouteWithChildren
  LojasRoute: typeof LojasRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  EntrarEntregadorSlugRoute: typeof EntrarEntregadorSlugRoute
  EntregadorIdRoute: typeof EntregadorIdRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PedidoIdRoute: typeof PedidoIdRoute
  EntregadorIndexRoute: typeof EntregadorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregadores': {
      id: '/entregadores'
      path: '/entregadores'
      fullPath: '/entregadores'
      preLoaderRoute: typeof EntregadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregadores/': {
      id: '/entregadores/'
      path: '/'
      fullPath: '/entregadores/'
      preLoaderRoute: typeof EntregadoresIndexRouteImport
      parentRoute: typeof EntregadoresRoute
    }
    '/entregador/': {
      id: '/entregador/'
      path: '/entregador'
      fullPath: '/entregador/'
      preLoaderRoute: typeof EntregadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregadores/perfil': {
      id: '/entregadores/perfil'
      path: '/perfil'
      fullPath: '/entregadores/perfil'
      preLoaderRoute: typeof EntregadoresPerfilRouteImport
      parentRoute: typeof EntregadoresRoute
    }
    '/entregadores/parceiros': {
      id: '/entregadores/parceiros'
      path: '/parceiros'
      fullPath: '/entregadores/parceiros'
      preLoaderRoute: typeof EntregadoresParceirosRouteImport
      parentRoute: typeof EntregadoresRoute
    }
    '/entregadores/painel': {
      id: '/entregadores/painel'
      path: '/painel'
      fullPath: '/entregadores/painel'
      preLoaderRoute: typeof EntregadoresPainelRouteImport
      parentRoute: typeof EntregadoresRoute
    }
    '/entregadores/nova-senha': {
      id: '/entregadores/nova-senha'
      path: '/nova-senha'
      fullPath: '/entregadores/nova-senha'
      preLoaderRoute: typeof EntregadoresNovaSenhaRouteImport
      parentRoute: typeof EntregadoresRoute
    }
    '/entregadores/login': {
      id: '/entregadores/login'
      path: '/login'
      fullPath: '/entregadores/login'
      preLoaderRoute: typeof EntregadoresLoginRouteImport
      parentRoute: typeof EntregadoresRoute
    }
    '/entregadores/cadastro': {
      id: '/entregadores/cadastro'
      path: '/cadastro'
      fullPath: '/entregadores/cadastro'
      preLoaderRoute: typeof EntregadoresCadastroRouteImport
      parentRoute: typeof EntregadoresRoute
    }
    '/entregador/$id': {
      id: '/entregador/$id'
      path: '/entregador/$id'
      fullPath: '/entregador/$id'
      preLoaderRoute: typeof EntregadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar-entregador/$slug': {
      id: '/entrar-entregador/$slug'
      path: '/entrar-entregador/$slug'
      fullPath: '/entrar-entregador/$slug'
      preLoaderRoute: typeof EntrarEntregadorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/': {
      id: '/_authenticated/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof AuthenticatedMasterIndexRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/empresa/': {
      id: '/_authenticated/empresa/'
      path: '/'
      fullPath: '/empresa/'
      preLoaderRoute: typeof AuthenticatedEmpresaIndexRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/master/usuarios': {
      id: '/_authenticated/master/usuarios'
      path: '/usuarios'
      fullPath: '/master/usuarios'
      preLoaderRoute: typeof AuthenticatedMasterUsuariosRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/master/seguranca': {
      id: '/_authenticated/master/seguranca'
      path: '/seguranca'
      fullPath: '/master/seguranca'
      preLoaderRoute: typeof AuthenticatedMasterSegurancaRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/master/relatorios': {
      id: '/_authenticated/master/relatorios'
      path: '/relatorios'
      fullPath: '/master/relatorios'
      preLoaderRoute: typeof AuthenticatedMasterRelatoriosRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/master/planos': {
      id: '/_authenticated/master/planos'
      path: '/planos'
      fullPath: '/master/planos'
      preLoaderRoute: typeof AuthenticatedMasterPlanosRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/master/mensalidades': {
      id: '/_authenticated/master/mensalidades'
      path: '/mensalidades'
      fullPath: '/master/mensalidades'
      preLoaderRoute: typeof AuthenticatedMasterMensalidadesRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/master/entregadores': {
      id: '/_authenticated/master/entregadores'
      path: '/entregadores'
      fullPath: '/master/entregadores'
      preLoaderRoute: typeof AuthenticatedMasterEntregadoresRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/master/empresas': {
      id: '/_authenticated/master/empresas'
      path: '/empresas'
      fullPath: '/master/empresas'
      preLoaderRoute: typeof AuthenticatedMasterEmpresasRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/empresa/relatorios': {
      id: '/_authenticated/empresa/relatorios'
      path: '/relatorios'
      fullPath: '/empresa/relatorios'
      preLoaderRoute: typeof AuthenticatedEmpresaRelatoriosRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/produtos': {
      id: '/_authenticated/empresa/produtos'
      path: '/produtos'
      fullPath: '/empresa/produtos'
      preLoaderRoute: typeof AuthenticatedEmpresaProdutosRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/planos': {
      id: '/_authenticated/empresa/planos'
      path: '/planos'
      fullPath: '/empresa/planos'
      preLoaderRoute: typeof AuthenticatedEmpresaPlanosRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/pedidos-simples': {
      id: '/_authenticated/empresa/pedidos-simples'
      path: '/pedidos-simples'
      fullPath: '/empresa/pedidos-simples'
      preLoaderRoute: typeof AuthenticatedEmpresaPedidosSimplesRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/pedidos': {
      id: '/_authenticated/empresa/pedidos'
      path: '/pedidos'
      fullPath: '/empresa/pedidos'
      preLoaderRoute: typeof AuthenticatedEmpresaPedidosRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/pdv': {
      id: '/_authenticated/empresa/pdv'
      path: '/pdv'
      fullPath: '/empresa/pdv'
      preLoaderRoute: typeof AuthenticatedEmpresaPdvRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/mesas': {
      id: '/_authenticated/empresa/mesas'
      path: '/mesas'
      fullPath: '/empresa/mesas'
      preLoaderRoute: typeof AuthenticatedEmpresaMesasRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/entregadores': {
      id: '/_authenticated/empresa/entregadores'
      path: '/entregadores'
      fullPath: '/empresa/entregadores'
      preLoaderRoute: typeof AuthenticatedEmpresaEntregadoresRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/cupons': {
      id: '/_authenticated/empresa/cupons'
      path: '/cupons'
      fullPath: '/empresa/cupons'
      preLoaderRoute: typeof AuthenticatedEmpresaCuponsRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/configuracoes': {
      id: '/_authenticated/empresa/configuracoes'
      path: '/configuracoes'
      fullPath: '/empresa/configuracoes'
      preLoaderRoute: typeof AuthenticatedEmpresaConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/clientes': {
      id: '/_authenticated/empresa/clientes'
      path: '/clientes'
      fullPath: '/empresa/clientes'
      preLoaderRoute: typeof AuthenticatedEmpresaClientesRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/categorias': {
      id: '/_authenticated/empresa/categorias'
      path: '/categorias'
      fullPath: '/empresa/categorias'
      preLoaderRoute: typeof AuthenticatedEmpresaCategoriasRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/avaliacoes': {
      id: '/_authenticated/empresa/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/empresa/avaliacoes'
      preLoaderRoute: typeof AuthenticatedEmpresaAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
    '/_authenticated/empresa/analytics': {
      id: '/_authenticated/empresa/analytics'
      path: '/analytics'
      fullPath: '/empresa/analytics'
      preLoaderRoute: typeof AuthenticatedEmpresaAnalyticsRouteImport
      parentRoute: typeof AuthenticatedEmpresaRouteRoute
    }
  }
}

interface AuthenticatedEmpresaRouteRouteChildren {
  AuthenticatedEmpresaAnalyticsRoute: typeof AuthenticatedEmpresaAnalyticsRoute
  AuthenticatedEmpresaAvaliacoesRoute: typeof AuthenticatedEmpresaAvaliacoesRoute
  AuthenticatedEmpresaCategoriasRoute: typeof AuthenticatedEmpresaCategoriasRoute
  AuthenticatedEmpresaClientesRoute: typeof AuthenticatedEmpresaClientesRoute
  AuthenticatedEmpresaConfiguracoesRoute: typeof AuthenticatedEmpresaConfiguracoesRoute
  AuthenticatedEmpresaCuponsRoute: typeof AuthenticatedEmpresaCuponsRoute
  AuthenticatedEmpresaEntregadoresRoute: typeof AuthenticatedEmpresaEntregadoresRoute
  AuthenticatedEmpresaMesasRoute: typeof AuthenticatedEmpresaMesasRoute
  AuthenticatedEmpresaPdvRoute: typeof AuthenticatedEmpresaPdvRoute
  AuthenticatedEmpresaPedidosRoute: typeof AuthenticatedEmpresaPedidosRoute
  AuthenticatedEmpresaPedidosSimplesRoute: typeof AuthenticatedEmpresaPedidosSimplesRoute
  AuthenticatedEmpresaPlanosRoute: typeof AuthenticatedEmpresaPlanosRoute
  AuthenticatedEmpresaProdutosRoute: typeof AuthenticatedEmpresaProdutosRoute
  AuthenticatedEmpresaRelatoriosRoute: typeof AuthenticatedEmpresaRelatoriosRoute
  AuthenticatedEmpresaIndexRoute: typeof AuthenticatedEmpresaIndexRoute
}

const AuthenticatedEmpresaRouteRouteChildren: AuthenticatedEmpresaRouteRouteChildren =
  {
    AuthenticatedEmpresaAnalyticsRoute: AuthenticatedEmpresaAnalyticsRoute,
    AuthenticatedEmpresaAvaliacoesRoute: AuthenticatedEmpresaAvaliacoesRoute,
    AuthenticatedEmpresaCategoriasRoute: AuthenticatedEmpresaCategoriasRoute,
    AuthenticatedEmpresaClientesRoute: AuthenticatedEmpresaClientesRoute,
    AuthenticatedEmpresaConfiguracoesRoute:
      AuthenticatedEmpresaConfiguracoesRoute,
    AuthenticatedEmpresaCuponsRoute: AuthenticatedEmpresaCuponsRoute,
    AuthenticatedEmpresaEntregadoresRoute:
      AuthenticatedEmpresaEntregadoresRoute,
    AuthenticatedEmpresaMesasRoute: AuthenticatedEmpresaMesasRoute,
    AuthenticatedEmpresaPdvRoute: AuthenticatedEmpresaPdvRoute,
    AuthenticatedEmpresaPedidosRoute: AuthenticatedEmpresaPedidosRoute,
    AuthenticatedEmpresaPedidosSimplesRoute:
      AuthenticatedEmpresaPedidosSimplesRoute,
    AuthenticatedEmpresaPlanosRoute: AuthenticatedEmpresaPlanosRoute,
    AuthenticatedEmpresaProdutosRoute: AuthenticatedEmpresaProdutosRoute,
    AuthenticatedEmpresaRelatoriosRoute: AuthenticatedEmpresaRelatoriosRoute,
    AuthenticatedEmpresaIndexRoute: AuthenticatedEmpresaIndexRoute,
  }

const AuthenticatedEmpresaRouteRouteWithChildren =
  AuthenticatedEmpresaRouteRoute._addFileChildren(
    AuthenticatedEmpresaRouteRouteChildren,
  )

interface AuthenticatedMasterRouteRouteChildren {
  AuthenticatedMasterEmpresasRoute: typeof AuthenticatedMasterEmpresasRoute
  AuthenticatedMasterEntregadoresRoute: typeof AuthenticatedMasterEntregadoresRoute
  AuthenticatedMasterMensalidadesRoute: typeof AuthenticatedMasterMensalidadesRoute
  AuthenticatedMasterPlanosRoute: typeof AuthenticatedMasterPlanosRoute
  AuthenticatedMasterRelatoriosRoute: typeof AuthenticatedMasterRelatoriosRoute
  AuthenticatedMasterSegurancaRoute: typeof AuthenticatedMasterSegurancaRoute
  AuthenticatedMasterUsuariosRoute: typeof AuthenticatedMasterUsuariosRoute
  AuthenticatedMasterIndexRoute: typeof AuthenticatedMasterIndexRoute
}

const AuthenticatedMasterRouteRouteChildren: AuthenticatedMasterRouteRouteChildren =
  {
    AuthenticatedMasterEmpresasRoute: AuthenticatedMasterEmpresasRoute,
    AuthenticatedMasterEntregadoresRoute: AuthenticatedMasterEntregadoresRoute,
    AuthenticatedMasterMensalidadesRoute: AuthenticatedMasterMensalidadesRoute,
    AuthenticatedMasterPlanosRoute: AuthenticatedMasterPlanosRoute,
    AuthenticatedMasterRelatoriosRoute: AuthenticatedMasterRelatoriosRoute,
    AuthenticatedMasterSegurancaRoute: AuthenticatedMasterSegurancaRoute,
    AuthenticatedMasterUsuariosRoute: AuthenticatedMasterUsuariosRoute,
    AuthenticatedMasterIndexRoute: AuthenticatedMasterIndexRoute,
  }

const AuthenticatedMasterRouteRouteWithChildren =
  AuthenticatedMasterRouteRoute._addFileChildren(
    AuthenticatedMasterRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEmpresaRouteRoute: typeof AuthenticatedEmpresaRouteRouteWithChildren
  AuthenticatedMasterRouteRoute: typeof AuthenticatedMasterRouteRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEmpresaRouteRoute: AuthenticatedEmpresaRouteRouteWithChildren,
  AuthenticatedMasterRouteRoute: AuthenticatedMasterRouteRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EntregadoresRouteChildren {
  EntregadoresCadastroRoute: typeof EntregadoresCadastroRoute
  EntregadoresLoginRoute: typeof EntregadoresLoginRoute
  EntregadoresNovaSenhaRoute: typeof EntregadoresNovaSenhaRoute
  EntregadoresPainelRoute: typeof EntregadoresPainelRoute
  EntregadoresParceirosRoute: typeof EntregadoresParceirosRoute
  EntregadoresPerfilRoute: typeof EntregadoresPerfilRoute
  EntregadoresIndexRoute: typeof EntregadoresIndexRoute
}

const EntregadoresRouteChildren: EntregadoresRouteChildren = {
  EntregadoresCadastroRoute: EntregadoresCadastroRoute,
  EntregadoresLoginRoute: EntregadoresLoginRoute,
  EntregadoresNovaSenhaRoute: EntregadoresNovaSenhaRoute,
  EntregadoresPainelRoute: EntregadoresPainelRoute,
  EntregadoresParceirosRoute: EntregadoresParceirosRoute,
  EntregadoresPerfilRoute: EntregadoresPerfilRoute,
  EntregadoresIndexRoute: EntregadoresIndexRoute,
}

const EntregadoresRouteWithChildren = EntregadoresRoute._addFileChildren(
  EntregadoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EntregadoresRoute: EntregadoresRouteWithChildren,
  LojasRoute: LojasRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  EntrarEntregadorSlugRoute: EntrarEntregadorSlugRoute,
  EntregadorIdRoute: EntregadorIdRoute,
  LojaSlugRoute: LojaSlugRoute,
  PedidoIdRoute: PedidoIdRoute,
  EntregadorIndexRoute: EntregadorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
